### ISSUE TITLE
cf --qstat is ridiculously slow when a significant number of jobs is running

### ISSUE THREAD

**Issue by s-andrews** [ewels/clusterflow#100]
```
$ time qstat -u "*" > /dev/null
real    0m0.101s
user    0m0.066s
sys     0m0.010s

$ time cf --qstatall > /dev/null
real    3m43.681s
user    3m42.923s
sys     0m0.467s

======================================================================
 Summary Job Counts
======================================================================
 Cluster Flow Pipelines:      9
 Running Jobs:              534
 Queued (Resources):       3492
 Jobs being deleted:         16
```

**Comment by s-andrews** [comment]
It looks like this is due to how crappily slow XML::Simple is at building the complete data structure from the XML document.

**Comment by s-andrews** [comment]
So apparently the problems with XML::Simple are well known:

http://www.perlmonks.org/?node_id=409517

They can be improved a *lot* by changing the back end parser used.  XML::Parser seems to the one you want.  If I switch the parsing to this then:

$ time cf --qstatall > /dev/null

real    0m19.179s
user    0m18.815s
sys     0m0.279s

..which is still a bit slower than I'd like but it's a lot better than before.  The proper answer is probably to use a SAX interface and parse it on the fly using a state based parser, but that's a bit further off.

I'll submit a patch.

**Comment by ewels** [comment]
Wow, that is crappy. I was going to say that it works fine for me, but the slurm parser doesn't use XML so that's probably why.

I wrote this code aages ago though, so not sure why this would be a new problem for you guys?

**Comment by FelixKrueger** [comment]
The problem isn't new, we simply chose to not complain about it. Now that we are doing the configuration of the new version we might as well whine about it ...

**Comment by s-andrews** [comment]
Pull request submitted.

To be honest I've never used cf --qstat but we've hit another problem with the new version which that might have been the answer to - I'll be in touch about that one!

**Comment by ewels** [comment]
Brilliant, thanks! Yes I'm not surprised that you don't usually use it if it takes 3 minutes to return anything :) I use it all the time, even to monitor non-cluster flow jobs, I much prefer it to the default queue monitor output (it has pretty colours 😍 )

**Comment by ewels** [comment]
ps. Another tip to make `cf --qstat` more usable:
```
alias qs='cf --qstat'
```

**Comment by s-andrews** [comment]
There's another bug report coming about that :-)

On our system the job ids come out as white on a light yellow background...


From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae3326d4d4a239724da564732aa5808759403d5e00892cf0000000113836c849
2a169ce09a5fae9@reply.github.com>
Date:  Thursday, 23 June 2016 at 10:23
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>, Author <author@noreply.github.com>
Subject:  Re: [ewels/clusterflow] cf --qstat is ridiculously slow when a
significant number of jobs is running (#100)


Brilliant, thanks! Yes I'm not surprised that you don't usually use it if it
takes 3 minutes to return anything :) I use it all the time, even to monitor
non-cluster flow jobs, I much prefer it to the default queue monitor output
(it has pretty colours 😍 )

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ewels/clusterflow/issues/100#issuecomment-227995717> ,
or mute the thread 
<https://github.com/notifications/unsubscribe/AHx643LA0DZlF3E573WtMLSjtiGA0F
hFks5qOlCEgaJpZM4I8l7P> .

**Comment by ewels** [comment]
Yeah, it's always done that - you disable it by running `cf --setup` and setting `@colourful 0` in the config file. You guys just did it so long ago that you've forgotten 😉

**Comment by ewels** [comment]
@FelixKrueger suggested that colourful output should be opt-in instead of opt-out, and I'm inclined to agree.

**Comment by s-andrews** [comment]
Surely there must be a less controversial colour code to use?  All of the
other colours come out OK - just that one sucks.


From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae3f9ec1fd956edfb77c370874c4779aa5b9ea875c792cf0000000113836f3e9
2a169ce09a5fae9@reply.github.com>
Date:  Thursday, 23 June 2016 at 10:34
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>, Author <author@noreply.github.com>
Subject:  Re: [ewels/clusterflow] cf --qstat is ridiculously slow when a
significant number of jobs is running (#100)


Yeah, it's always done that - you disable it by running cf --setup and
setting @colourful 0 in the config file. You guys just did it so long ago
that you've forgotten 😉

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ewels/clusterflow/issues/100#issuecomment-227998358> ,
or mute the thread 
<https://github.com/notifications/unsubscribe/AHx648sCNJeUOUz6_cyZ_R0nJudmzk
A_ks5qOlM-gaJpZM4I8l7P> .

**Comment by ewels** [comment]
_* tries to defend colour choices.. *_

Ok yeah, it does suck a bit. It is at least readable on my colour scheme and stands out (which was the desired effect):
![image](https://cloud.githubusercontent.com/assets/465550/16298777/54c32ed4-3937-11e6-8e0b-2d6edfaeb55e.png)

I think it looked better with my previous light colour scheme when working at the BI. But maybe just using coloured text without the background would be less sucky.

How about... Green text?

Phil

**Comment by ewels** [comment]
See #102
