### ISSUE TITLE
Use less controversial colours for --qstatcols

### ISSUE THREAD

**Issue by ewels** [ewels/clusterflow#102]
Yellow on a white background upsets some people (everyone except me, actually). Switch this to green on a normal background, or something else less offensive.

**Comment by ewels** [comment]
Firstly, I'm pretty sure that colours _are_ off by default? So I'm guessing that @FelixKrueger has `@colourful` in his cluster flow config without realising it. Let me know if this isn't the case and I'll look into it more.

**Comment by FelixKrueger** [comment]
Yes I ran the configuration again and the text convinced me that it would now look nice. Wasn't aware that it had not changed in the meantime and it was still awkward. Deleting `@colourcful` reverted it back to a clean B&W.

**Comment by ewels** [comment]
Sorry, you were too quick - I hadn't pushed the changes yet as I was messing around trying to test them myself. Now pushed, so you should be able to try again.

**Comment by ewels** [comment]
Screen grabs of new colour scheme on my display:
![image](https://cloud.githubusercontent.com/assets/465550/16772755/b180b3e4-4855-11e6-84d8-d4bd7ecbb66b.png)

![image](https://cloud.githubusercontent.com/assets/465550/16772913/2e718a40-4856-11e6-8509-c12614911826.png)

Hmm, think I might make the queueing jobs yellow instead of cyan.

**Comment by ewels** [comment]
Better now I think:
![image](https://cloud.githubusercontent.com/assets/465550/16772953/5996f520-4856-11e6-9879-3ffa9438823d.png)

@FelixKrueger / anyone else have any screen shots of how these look for them?

**Comment by ewels** [comment]
ok, I think I'm happy with this change. Closing.
