### ISSUE TITLE
Posible to specify output dir ?

### ISSUE THREAD

**Issue by arontommi** [ewels/clusterflow#118]
Well the title says it all, 
Big fan of cf, been using it allot on uppmax. Is there a way specify output locations for modules ?

**Comment by ewels** [comment]
Hi @arontommi,

Not currently, no sorry. How exactly do you see this working - you mean having the output from each CF module go into a subdirectory? I guess that this could be possible..

Phil

**Comment by arontommi** [comment]
This is mainly a nonissue, i was thinking this in the sense of being able to work on raw files from a space limited backed up directory, and spiting out into nobackup.

**Comment by ewels** [comment]
Ah I see - so just have all output files end up in a different directory? That one is easier.. 😌  Cluster Flow can't do this for you, but it's pretty simple to do using softlinks; I do this myself all the time on UPPMAX.

For example:

```bash
cd /proj/b2017001/nobackup/private/my_proj/
ln -s /proj/b2017001/private/my_proj/*.fastq.gz .
cf --genome GRCh37 fastq_star *.fastq.gz
```

The output files are always created in the working directory, so in theory I think you may even just be able to run in `nobackup` and specify the path to the raw data wherever it is. However, I think that from memory that I may have run into issues where some output filenames are created using the complete filenames, so `/abs/path/file.fastq` becomes `/abs/path/file.bam`, meaning that it's still saved in the input file directory. Given the simplicity of the softlinking solution I'm not in a huge rush to address this though.

Hope this helps! Let me know if it works / you run into any problems.

Phil

**Comment by arontommi** [comment]
Great thanks! was t still a little wet behind the ears :)

**Comment by ewels** [comment]
No problem at all! Glad that you're finding Cluster Flow useful :)
