### ISSUE TITLE
cf --qstatall throws errors

### ISSUE THREAD

**Issue by FelixKrueger** [ewels/clusterflow#14]
`cf --qstatall` currently produces a few hundred errors such as:
```perl
Deep recursion on subroutine "CF::Headnodehelpers::parse_job_dependency_hash" at /bi/apps/clusterflow/0.4_devel/source/CF/Headnodehelpers.pm line 298.
Deep recursion on subroutine "CF::Headnodehelpers::parse_job_dependency_hash" at /bi/apps/clusterflow/0.4_devel/source/CF/Headnodehelpers.pm line 298.
...
Use of uninitialized value in string eq at /bi/apps/clusterflow/0.4_devel/source/CF/Headnodehelpers.pm line 459.
Use of uninitialized value in string eq at /bi/apps/clusterflow/0.4_devel/source/CF/Headnodehelpers.pm line 459.
...
```
Using GRID Engine and Cluster Flow 0.4_devel

**Comment by ewels** [comment]
@FelixKrueger - does this bug still happen? If so, could you please copy and paste in the lines of code that the errors refer to? The devel code isn't stable so it could represent various different states :confused:

Mind you - looking at the [current state](https://github.com/ewels/clusterflow/blob/v0.4devel/source/CF/Headnodehelpers.pm#L459) of that line, it looks like a possible candidate.

Any ideas how it could be being called with > 0 `$children` but no `${$hashref}{$key}{module}` variable?

If you're still able to get the error to happen, could you stick in a `Data::Dumper` warning in there to try and figure out what's going on?

Difficult to bug test from here without access to any grid engine servers :disappointed:

**Comment by FelixKrueger** [comment]
Sorry can’t reproduce the errors right now anymore.

**Comment by ewels** [comment]
Great, that's good news ;) I'll close this issue for now then - as with the others, feel free to re-open or start a new issue if it crops up again. Apologies for taking ages to reply...
