### ISSUE TITLE
Bismark methylation extractor error

### ISSUE THREAD

**Issue by ewels** [ewels/clusterflow#20]
Bismark methylation extrator module threw the following warning and later failed:

```
Reference found where even-sized list expected at /bi/apps/clusterflow/0.4_devel/modules/../source/CF/Helpers.pm line 262.
```

This somehow seems to then lead to bismark not being given a reference genome:
```
bismark_methylation_extractor --multi 4  --ignore_r2 2 --bedGraph --counts  --cytosine_report --gzip -p --no_overlap --report  lane2_5pc_SCM_ox_ATCACGTT_L002_R1_val_1.fq.gz_bismark_bt2_pe.deduplicated.bam
```
```
Please specify a genome folder to proceed (full path only)
```

_Note_ - I was messing around with this command recently to get it to do the coverage analysis, so the first warning could be a red herring.

**Comment by ewels** [comment]
@FelixKrueger - I'm a bit confused by this bug report. I think our code bases must be different as [line 262](https://github.com/ewels/clusterflow/blob/v0.4devel/source/CF/Helpers.pm#L262) shouldn't be able to generate that first warning.

Could you dig a little further back from the warning messages to find the code responsible please? Or let me know the steps I need to do to reproduce the error..

**Comment by FelixKrueger** [comment]
Maybe it is not worth digging much deeper for this at the current time, we have changed so many things lately. How about I report back if I find a new problem? Apparently I’ve now got push access to our BI_devel version for CF, from which you can merge things…

**Comment by ewels** [comment]
Ok, I'm closing this for now then. Feel free to re-open or create a new issue if this turns up again.
