### ISSUE TITLE
Remove SGE vf memory option

### ISSUE THREAD

**Issue by ewels** [ewels/clusterflow#26]
Remove the option to use `vf` for memory assignment. Always use `h_vmem` instead.

@stu2 - is this going to mess up your work flow at all, or is this ok?

**Comment by s-andrews** [comment]
In a normal grid engine setup vf doesn't really do anything.  It's not enforced by the shepherd and it's not used by the scheduler.  If we use h_vmem then at least it's enforced even if it's not used by the scheduler without some additional configuration.

**Comment by ewels** [comment]
Ok - so it shouldn't do any damage to use `h_vmem` for everything?

**Comment by s-andrews** [comment]
That was my take on it, hence removing the option rather than just modifying our default.

**Comment by ewels** [comment]
Great. I'll remove everything to do with `vf` or `h_vmem` and just hardwire these into the grid engine job submission commands then.

**Comment by ewels** [comment]
Handled in https://github.com/ewels/clusterflow/pull/27
