### ISSUE TITLE
Specify expected time for modules

### ISSUE THREAD

**Issue by ewels** [ewels/clusterflow#45]
Most HPC systems have an option to specify expected job execution time, which affects queuing. At the moment, Cluster Flow basically ignores this (SLURM jobs default to two days for example), which hurts our queue performance.

It would be nice if modules are able to specify how long they thing they'll take to run. For  SLURM jobs, if this is less than 15 minutes we can get the bonus of specifying `--qos=short` which will make them much faster.

**Comment by ewels** [comment]
@s-andrews: I assume GRIDEngine has some kind of similar support? Would you be interested in adding this for SGE?

We have some nice [resource usage tools](http://www.uppmax.uu.se/discovering-job-resource-usage-with-jobstats) which I'm might try to use to optimise module requests. I'll try to write some sensible time estimation code for modules that I use as well, rather than just flat estimates. Obviously setting these too low will be very annoying if jobs get cancelled, the increased queue efficiency should be worth it though.

**Comment by s-andrews** [comment]
GridEngine has qacct which records some stats for each job run (CPU, runtime and memory mostly).  We've been tweaking the existing limits to match what we see from real jobs as a lot of the older limits proved to be a little under where they needed to be.

I'm sure GridEngine can be set up to take runtime into account when submitting jobs (normally I think people just set up short and long queues with different limits on them), but it's not something we use.

**Comment by ewels** [comment]
Ok, sounds good - if there are any new limit tweaks you've done recently, it'd be good to see them to give me a head start on fine tuning all of this. I'll implement the time estimation thing as a parameter for the `qsub` submission string, so it'll be totally optional and there if you want it in the future.

**Comment by s-andrews** [comment]
OK, will check if we have any unsubmitted tweaks.

I was having problem getting our branch back in line with your mainline
version.  I couldn't generate a pull which seemed to bring them back
together.  If you had a second to see if you could figure it out that would
help us out (I think you have commit privileges on our branch).

Simon.

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae32412933d843b647f2bbbc7978d66bc81bfec222492cf000000011132852d9
2a169ce03c416a2@reply.github.com>
Date:  Tuesday, 31 March 2015 16:54
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  Re: [clusterflow] Specify expected time for modules (#45)


Ok, sounds good - if there are any new limit tweaks you've done recently,
it'd be good to see them to give me a head start on fine tuning all of this.
I'll implement the time estimation thing as a parameter for the qsub
submission string, so it'll be totally optional and there if you want it in
the future.

‹
Reply to this email directly or view it on GitHub
<https://github.com/ewels/clusterflow/issues/45#issuecomment-88141029> .

**Comment by ewels** [comment]
The PR [looks like](https://github.com/ewels/clusterflow/compare/v0.4devel...s-andrews:master) there's only one change you've done from the 0.4 devel branch, adding requirements to `cf_download`. There's a merge conflict though, so I've probably done something similar at my end.

Not sure it's worth faffing with the merge for now if that's the only change.

**Comment by s-andrews** [comment]
We'd made some changes to pipelines, but maybe those had already been pulled
in.  I've just done a git status on our working copy and it says there's
nothing else to commit.

If the merge is too much of a pain we'll just delete and re-fork when you
get the next release out.

Simon.

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae304920be0a0af262bd20a188b8cd6d7f86a6bd5c692cf00000001113286739
2a169ce03c416a2@reply.github.com>
Date:  Tuesday, 31 March 2015 16:59
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  Re: [clusterflow] Specify expected time for modules (#45)


The PR looks like 
<https://github.com/ewels/clusterflow/compare/v0.4devel...s-andrews:master>
there's only one change you've done from the 0.4 devel branch, adding
requirements to cf_download. There's a merge conflict though, so I've
probably done something similar at my end.

Not sure it's worth faffing with the merge for now if that's the only
change.

‹
Reply to this email directly or view it on GitHub
<https://github.com/ewels/clusterflow/issues/45#issuecomment-88142444> .

**Comment by ewels** [comment]
Sounds good..

**Comment by ewels** [comment]
Done as part of #47

**Comment by ewels** [comment]
See #56 for the code changes.
