### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by s-andrews** [ewels/clusterflow#72]
Since we're thinking about future stuff I thought I'd document a couple of things we started playing with here, but should probably go upstream.

1) For all modules involving genomes, the modules should write the name of the genome used into the output file name.  It would be really helpful to have this in place so you can quickly see what was done, and also not get clashes if you map the same data to multiple genomes.

2) The logic for the requirements of pipelines is messed up.  At the moment it's the pipeline which says whether it requires a genome, index, annotation file etc, but that's the wrong place to determine that.  Requirements should be part of the module API since its the modules which require them.  The requirements for a pipeline would therefore be the combined set of requirements for all of the modules within that pipeline.

**Comment by ewels** [comment]
Made this into two separate issues.
