### ISSUE TITLE
Have genome details available in modules

### ISSUE THREAD

**Issue by ewels** [ewels/clusterflow#75]
Have information about the reference genome (name, build, key etc) available in a variable for modules to use.

**Comment by s-andrews** [comment]
The idea for this is that for modules which use the genome it would be useful to be able to write the genome alias into the output file.  For this we wouldn't need the actual files uses (fasta, indices etc), but rather the short name listed in the conf file and which the user would have specified when they launched clusterflow with the --genome parameter.

**Comment by ewels** [comment]
Looking at [the code](https://github.com/ewels/clusterflow/blob/master/source/CF/Helpers.pm#L231) I think that because of a bonus _"and everything else"_ parsing line I added, this should already be available to modules. Untested, but something like this:

```perl
my $genome = $cf{'config'}{'genome'};
```

The same goes for anything else in a runfile that has a line that begins with an `@`, apart from `@notification` and `@reference` which are parsed separately:

```
@split_files    2
@total_cores    16
@total_mem      128G
@email          ...
@notification   suspend
@genome         GRCh37
@reference      fasta    /path/to/ref
@force_paired_end
```

This should do the job?

**Comment by ewels** [comment]
Closing this issue as already implemented. Feel free to reopen if I've missed something.
