### ISSUE TITLE
Cluster Flow for Perl 5.22 + 

### ISSUE THREAD

**Issue by machbio** [ewels/clusterflow#81]
ClusterFlow Executable needs to be changed - as there are lot of regex errors with Perl 5.22+. I have tested only on Perl 5.22.1

> Unescaped left brace in regex is deprecated, passed through in regex;

These are not warnings anymore - as they are syntax errors since 5.21.1;

https://metacpan.org/pod/release/PCM/perl-5.21.3/pod/perl5211delta.pod#A-literal-should-now-be-escaped-in-a-pattern

**Comment by ewels** [comment]
Hi @machbio - thanks for the error report. Is it possible to paste the list of errors to save some time?

Cheers,

Phil

**Comment by machbio** [comment]
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE  CONTENT }}/ at /hpc/home/user/softwares/clusterflow/source/CF/Helpers.pm line 835.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE  CF_VERSION }}/ at /hpc/home/user/softwares/clusterflow/source/CF/Helpers.pm line 836.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE  PAGE_TITLE }}/ at /hpc/home/user/softwares/clusterflow/source/CF/Helpers.pm line 838.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE  CONTENT }}/ at /hpc/home/user/softwares/clusterflow/source/CF/Helpers.pm line 839.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE  CF_VERSION }}/ at /hpc/home/user/softwares/clusterflow/source/CF/Helpers.pm line 840.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE command}}/ at /home/user/softwares/clusterflow/cf line 1124.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE job_id}}/ at /home/user/softwares/clusterflow/cf line 1125.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE outfn}}/ at /home/user/softwares/clusterflow/cf line 1126.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE cores}}/ at /home/user/softwares/clusterflow/cf line 1127.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE mem}}/ at /home/user/softwares/clusterflow/cf line 1128.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE time}}/ at /home/user/softwares/clusterflow/cf line 1129.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE priority}}/ at /home/user/softwares/clusterflow/cf line 1130.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE email}}/ at /home/user/softwares/clusterflow/cf line 1131.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE project}}/ at /home/user/softwares/clusterflow/cf line 1132.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE command}}/ at /home/user/softwares/clusterflow/cf line 1179.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE job_id}}/ at /home/user/softwares/clusterflow/cf line 1180.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE outfn}}/ at /home/user/softwares/clusterflow/cf line 1181.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE cores}}/ at /home/user/softwares/clusterflow/cf line 1182.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE mem}}/ at /home/user/softwares/clusterflow/cf line 1183.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE time}}/ at /home/user/softwares/clusterflow/cf line 1184.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE priority}}/ at /home/user/softwares/clusterflow/cf line 1185.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE notifications}}/ at /home/user/softwares/clusterflow/cf line 1186.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE email}}/ at /home/user/softwares/clusterflow/cf line 1187.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE project}}/ at /home/user/softwares/clusterflow/cf line 1188.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE command}}/ at /home/user/softwares/clusterflow/cf line 1258.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE job_id}}/ at /home/user/softwares/clusterflow/cf line 1259.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE outfn}}/ at /home/user/softwares/clusterflow/cf line 1260.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE cores}}/ at /home/user/softwares/clusterflow/cf line 1261.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE qname}}/ at /home/user/softwares/clusterflow/cf line 1262.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE mem}}/ at /home/user/softwares/clusterflow/cf line 1263.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE time}}/ at /home/user/softwares/clusterflow/cf line 1264.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE priority}}/ at /home/user/softwares/clusterflow/cf line 1265.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE notifications}}/ at /home/user/softwares/clusterflow/cf line 1266.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE email}}/ at /home/user/softwares/clusterflow/cf line 1267.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE project}}/ at /home/user/softwares/clusterflow/cf line 1268.

**Comment by ewels** [comment]
Brilliant, thanks! I am planning to allocate some time towards working on Cluster Flow in a month or so, I will add these Perl versions to the [travis config](https://github.com/ewels/clusterflow/blob/master/.travis.yml) for automated testing and try to fix the new bugs and warnings ready for the v0.4 release (which is very, very overdue).

So, not going to get fixed very soon, but it will happen eventually! Feel free to submit a pull request if you'd like to contribute instead.

Cheers,

Phil

**Comment by machbio** [comment]
Thank you @ewels - I do not know much perl - I am more into Python. So I have very limited knowledge about how it might affect the backward compatibility. 
If you are sure about the backward compatibility - I can make changes to the errors and submit a pull request.

**Comment by ewels** [comment]
I'm not sure either to be honest - my guess is that it should be fine though. These braces are used by a slightly dodgy self-written templating system (eg. [here](https://github.com/ewels/clusterflow/blob/master/cf#L1124-L1132)). We'll find out fast enough if it breaks backwards compatibility when you submit the PR, as Travis will throw lots of errors (it checks [multiple versions of perl](https://github.com/ewels/clusterflow/blob/master/.travis.yml#L3-L7)).

Phil

**Comment by machbio** [comment]
I see that you have only Master Branch - it will really help if you follow - http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/

I am hoping I can contribute towards clusterflow in the future..

**Comment by ewels** [comment]
Thanks @machbio - for smaller projects like this one where I'm basically the only person working on the code, I find git flow to be a bit excessive. I use branches if I'm pushing commits that break the tool, but otherwise I like the master branch to have the latest (semi-stable) development version of the code personally.

No worries about contributing, I will fix this issue but I'm just aware that it may take me a little time to get to it. Thanks again for reporting!
