### ISSUE TITLE
Get Bismark summary module to use new bismark command

### ISSUE THREAD

**Issue by ewels** [ewels/clusterflow#87]
The new [v16 release](https://github.com/FelixKrueger/Bismark/releases/tag/0.16.0) of Bismark included a new `bismark2summary` command which creates a summary report. Now that this is part of the core bismark package, there's no need to keep this code in a Cluster Flow module. So, we can massively simplify the [`bismark_summary_report`](https://github.com/ewels/clusterflow/blob/master/modules/bismark_summary_report.cfmod.pl) module and just get it to call the new `bismark2summary` command instead.

**Comment by ewels** [comment]
Would also be nice to add `--nucleotide_coverage` to the main bismark command.

**Comment by FelixKrueger** [comment]
Just as a word of warning, adding `--nucleotide_coverage` might add a few extra hours of processing time, at least for the first pass of the reference genome.

**Comment by ewels** [comment]
Yup, thanks for the heads up! I think I'll leave this for now, at least until FelixKrueger/Bismark#44 is cleared up and I've tested the extra time needed.
