### ISSUE TITLE
Restructure dependencies

### ISSUE THREAD

**Issue by s-andrews** [ewels/clusterflow#93]
Probably something to tackle after v0.4, and I know we've mentioned this before, but I thought I'd write it down.

The way that dependencies are structured in clusterflow doesn't work as well as it should.  At the moment depdendencies are written into pipelines and are checked when the pipeline is run.

Dependencies should be part of the module API, and that's the right place to check them.  Pipelines are just a collection of modules so you shouldn't need to put anything into the pipelines.  This would then make things work for both running a pipeline or a single module, and it would mean you don't have to update the pipeline if something changes in a module.

The mechanism for dependencies could also be simplified.  At the moment you're putting explicit fixed dependencies down which I guess makes life easier if you want to read through what's needed, but a simpler solution would be to do a sanity check run of each module and give it a chance to object.  This would be an API call where you pass it the config for the run and let it generate errors - you then present these back to the user before running the pipeline.  This would then let the module generate errors in context and not be limited in what it's combinations and conditions for errors would be.

What do you think?

**Comment by ewels** [comment]
When you say dependencies, do you mean reference genomes? I think that this is already implemented in the new code that I merged back to you? eg. See commit a2f78c23c1bb30071208ec7595c575cbc3f74e96 (dependency listed in the hisat2 module [here](https://github.com/ewels/clusterflow/blob/master/modules/hisat2.cfmod.pl#L35)).

**Comment by s-andrews** [comment]
Haven't looked at the code, but the pipelines in the latest version still
have dependencies listed at the top - these shouldn't be needed if they're
all handled in the modules.  Is that just left over syntax?

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae3bbb7d14f208f58fd870f482b579314157a1c171b92cf00000001137a29009
2a169ce0992acf8@reply.github.com>
Date:  Thursday, 16 June 2016 at 09:44
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>, Author <author@noreply.github.com>
Subject:  Re: [ewels/clusterflow] Restructure dependencies (#93)


When you say dependencies, do you mean reference genomes? I think that this
is already implemented in the new code that I merged back to you? eg. See
commit a2f78c2 
<https://github.com/ewels/clusterflow/commit/a2f78c23c1bb30071208ec7595c575c
bc3f74e96>  (dependency listed in the hisat2 module here
<https://github.com/ewels/clusterflow/blob/master/modules/hisat2.cfmod.pl#L3
5> ).


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ewels/clusterflow/issues/93#issuecomment-226424654> , or
mute the thread 
<https://github.com/notifications/unsubscribe/AHx64xOeTdBVtJpTqIpmafkFOnH8lX
nyks5qMQ0AgaJpZM4I3JuV> .

**Comment by ewels** [comment]
Do you have an example of such a pipeline? The files I'm looking at just have the help text and pipeline steps. _e.g._ the `fastq_star` pipeline looks like this:

```
/*
------------------------
FastQ to STAR Pipeline
------------------------
This pipeline takes FastQ files as input, runs FastQC, Trim Galore,
then aligns with STAR. The module requires a genome reference with a
corresponding STAR index base in the configuration.
*/

#fastqc
#trim_galore
	#star
```

**Comment by s-andrews** [comment]
Yeah - about that.

I looked at the first one (bam_preseq) and saw:

@require_python_package ngi_visualizations



..which again is something which applies to a module rather than a pipeline,
but now I've looked properly I can see all the rest has gone.



I'm a bit of a muppet some days.





From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae30d7ccb8f1a800c41f18be16da9e4b43d5df1227a92cf00000001137a2b2e9
2a169ce0992acf8@reply.github.com>
Date:  Thursday, 16 June 2016 at 09:54
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>, Author <author@noreply.github.com>
Subject:  Re: [ewels/clusterflow] Restructure dependencies (#93)


Do you have an example of such a pipeline? The files I'm looking at just
have the help text and pipeline steps. e.g. the fastq_star pipeline looks
like this:
/*
------------------------
FastQ to STAR Pipeline
------------------------
This pipeline takes FastQ files as input, runs FastQC, Trim Galore,
then aligns with STAR. The module requires a genome reference with a
corresponding STAR index base in the configuration.
*/

#fastqc
#trim_galore
    #star

You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ewels/clusterflow/issues/93#issuecomment-226426735> , or
mute the thread 
<https://github.com/notifications/unsubscribe/AHx64yIp-acIAqX0GWgiLIUDfjpEKW
LDks5qMQ8ugaJpZM4I3JuV> .

**Comment by ewels** [comment]
Ah yeah, I can see why you would be confused! That's a bit of a relic from when I was keen on getting Cluster Flow to run Python. I've gone off the idea a bit since then, mostly as `preseq_plot.cfmod.py` never really worked properly and required a SciLifeLab plotting library which isn't very portable.

This module is especially redundant with the arrival of MultiQC. I'll add an issue to remove this code.

**Comment by ewels** [comment]
See #94
