### ISSUE TITLE
Create genomes.d folder?

### ISSUE THREAD

**Issue by s-andrews** [ewels/clusterflow#96]
A suggestion (and an offer to actually code it!)

Our `genomes.config` file is getting a bit out of control and is quite difficult to manage since we have so many genomes in there.

Taking a leaf out of the linux config structure - how would you feel about creating a `genomes.d` folder into which you could place any number of `.config` files.  You could then split your configuration between these (eg one per assembly, one per species - whatever you liked) and the configuration would be read from all of them.  You could leave the original `genomes.config` in place so this wouldn't break anything for existing setups but would give some more flexibility as the scale of some of the installs started to increase.

**Comment by ewels** [comment]
Yup, that sounds fine. Where would this folder go? Same places as the config? (`installation_dir`, `~/.clusterflow/`, `cwd`)

**Comment by s-andrews** [comment]
Yes, it would go alongside the existing config file.

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae33989b40c5c147c3a8336511140ac6a5489e6f9c592cf00000001137b664e9
2a169ce09960363@reply.github.com>
Date:  Friday, 17 June 2016 at 08:18
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>, Author <author@noreply.github.com>
Subject:  Re: [ewels/clusterflow] Create genomes.d folder? (#96)


Yup, that sounds fine. Where would this folder go? Same places as the
config? (installation_dir, ~/.clusterflow/, cwd)


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ewels/clusterflow/issues/96#issuecomment-226698318> , or
mute the thread 
<https://github.com/notifications/unsubscribe/AHx64zUT6olcs84DxbWNyNrBwiKgrH
xeks5qMkpOgaJpZM4I4F1n> .

**Comment by ewels** [comment]
Closed in #98
